#!/bin/bash

# create the virtualenv
cd $WORKON_HOME
virtualenv --no-site-packages $1

# activate the virtualenv
source $1/bin/activate

# install anything in the new-env-packages.local file
pip install -r ~/djangowrapper/packages.local

# create the new django project
cd $1
bin/django-admin.py startproject $2

# create the postactivate script
echo "#!/bin/bash" >> $WORKON_HOME/$1/bin/postactivate
echo "#This hook is run after every virtualenv is activated." >> $WORKON_HOME/$1/bin/postactivate
echo "cd $WORKON_HOME/$1/$2" >> $WORKON_HOME/$1/bin/postactivate
chmod 775 $WORKON_HOME/$1/bin/postactivate

# insert the appropriate settings values into the settings.py file
SETTINGS=0
if [ -e ~/djangowrapper/settings.tpl ]
then
    cat ~/djangowrapper/settings.tpl | cat - $WORKON_HOME/$1/$2/$2/settings.py > temp && mv temp $WORKON_HOME/$1/$2/$2/settings.py
    SETTINGS=1
fi

echo
echo "New Django project created!"
echo
echo "Next steps:"
echo "  1. workon $1"
echo "  2. vi $2/settings.py"
echo

