#!/bin/bash

# create the virtualenv
cd $WORKON_HOME
virtualenv --no-site-packages $1

# activate the virtualenv
source $1/bin/activate

# install anything in the new-env-packages.local file
pip install -r ~/djangowrapper/packages.local

# create the new django project
cd $1
bin/django-admin.py startproject $2

# copy over a new settings.py if it exists
if [ -e ~/djangowrapper/settings.tpl ]
then
    cp ~/djangowrapper/settings.tpl $WORKON_HOME/$1/$2/settings.py
fi

